module.exports = {
  helloApiHandler: require('./helloApiHandler'),
  registerUserHandler: require('./registerUserHandler'),
  authenticateUserHandler: require('./authenticateUserHandler'),
  retrieveUserHandler: require('./retrieveUserHandler'),
  updateUserAvatarHandler: require('./updateUserAvatarHandler'),
  updateUserPasswordHandler: require('./updateUserPasswordHandler'),
  createPostHandler: require('./createPostHandler'),
  retrievePostHandler: require('./retrievePostHandler'),
  retrievePostsHandler: require('./retrievePostsHandler'),
  retrieveSavedPostsHandler: require('./retrieveSavedPostsHandler'),
  deletePostHandler: require('./deletePostHandler'),
  updatePostHandler: require('./updatePostHandler'),
  togglePrivatizePostHandler: require('./togglePrivatizePostHandler'),
  toggleLikePostHandler: require('./toggleLikePostHandler'),
  toggleSavePostHandler: require('./toggleSavePostHandler'),
  buyPostHandler: require('./buyPostHandler'),
  sellPostHandler: require('./sellPostHandler'),
  addCommentToPostHandler: require('./addCommentToPostHandler'),
  removeCommentFromPostHandler: require('./removeCommentFromPostHandler'),
}
