export const categories = [
  {
    image: '/categories/Disney.svg',
    headerImage: '/categories/Header-Disney.svg',
    name: 'Disney',
    slug: 'disney',
    route: '/catalog/disney',
  },
  {
    image: '/categories/Harry-Potter.svg',
    headerImage: '/categories/Header-Harry-Potter.svg',
    name: 'Harry Potter',
    slug: 'harry-potter',
    route: '/catalog/harry-potter',
  },
  {
    image: '/categories/Games.svg',
    headerImage: '/categories/Header-Games.svg',
    name: 'Games',
    slug: 'games',
    route: '/catalog/games',
  },
  {
    image: '/categories/Anime.svg',
    headerImage: '/categories/Header-Anime.svg',
    name: 'Anime',
    slug: 'anime',
    route: '/catalog/anime',
  },
  {
    image: '/categories/Music.svg',
    headerImage: '/categories/Header-Music.svg',
    name: 'Music',
    slug: 'music',
    route: '/catalog/music',
  },
  {
    image: '/categories/Movies-&-TV.svg',
    headerImage: '/categories/Header-Movies-And-TV.svg',
    name: 'Movies & TV',
    slug: 'movies-and-tv',
    route: '/catalog/movies-and-tv',
  },
  {
    image: '/categories/Animation.svg',
    headerImage: '/categories/Header-Animation.svg',
    name: 'Animation',
    slug: 'animation',
    route: '/catalog/animation',
  },
  {
    image: '/categories/Sports.svg',
    headerImage: '/categories/Header-Sports.svg',
    name: 'Sports',
    slug: 'sports',
    route: '/catalog/sports',
  },
]
