'use client'

import './globals.css'
import type { Metadata } from 'next'
import { useState } from 'react'
import Header from './components/Header'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isModalOpen, setIsModalOpen] = useState(false)

  return (
    <html lang="en" className="h-screen">
      <body className="flex flex-col h-screen">
        <Header />
        <main
          className={`flex flex-col grow ${
            !isModalOpen ? 'overflow-auto' : 'overflow-hidden'
          }`}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
